trigger:
- main

pool:
  name: default
  demands:
   - agent.name -equals $(agentname)
variables:
  project_test: '**/Quantum.Math.Api.Tests/Quantum.Math.Api.Tests.csproj'
  project_api: '**/Quantum.Math.Api/Quantum.Math.Api.csproj'
  buildPlatform: 'Any CPU'
  imageName: 'qm-api'


steps:
- task: DotNetCoreCLI@2
  displayName: 'Build Application'
  inputs:
    command: 'build'
    projects: '$(project_api)'

- task: DotNetCoreCLI@2
  name: 'Tests'
  displayName: 'Run Unit Tests'
  inputs:
    command: 'test'
    projects: '$(project_test)'
    
- task: Docker@2
  displayName: 'Docker Build and Push'
  inputs:
    containerRegistry: 'Docker Hub'
    repository: '$(dockerId)/$(imageName)'
    command: 'buildAndPush'
    Dockerfile: '**/prd.dockerfile'
    tags: |
      latest
      $(Build.BuildId)